<a href="https://colab.research.google.com/github/Aneekcodes/Complete-Python-Bootcamp/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#1
from sklearn.utils import resample
import pandas as pd
data=pd.read_csv('btissue.csv')
import numpy as np
np.shape(data)
X = data.iloc [:, 0:9]
X.head()
X1 =resample(X, n_samples=200, random_state=0)
X1.head(6)


I0     PA500       HFS  ...      Max IP          DR            P
44    172.515797  0.127235  0.038397  ...   19.322081   32.189821   174.933770
47    370.395725  0.104720  0.000000  ...   31.367031  112.715102   365.977651
64    391.000000  0.058119  0.011170  ...   22.131472   28.114244   400.994818
67    145.000000  0.117635  0.110305  ...   20.303082    6.166715   162.510927
67    145.000000  0.117635  0.110305  ...   20.303082    6.166715   162.510927
103  1600.000000  0.071908 -0.066323  ...  103.732704  432.129749  1475.371534

[6 rows x 9 columns]

In [13]:
#2
from sklearn.tree import DecisionTreeClassifier
predictors =data.iloc[:,0:9]
predictors.head()
target =data.iloc[:, 9]
target.head()
from sklearn.model_selection import train_test_split
predictors_train, predictors_test, target_train, target_test = train_test_split(predictors,target)
predictors_train.head()



I0     PA500       HFS  ...      Max IP          DR            P
95  1850.000000  0.073304  0.225497  ...  208.739975  249.353486  1908.177239
37   195.000000  0.139103  0.205251  ...   35.023827   13.294650   232.587628
17   300.000000  0.190066  0.166853  ...   51.353973   82.418192   387.078228
13   366.942379  0.280125  0.252026  ...   75.604324  155.322285   471.588195
33   301.304399  0.109781  0.035605  ...   29.045677   57.720030   335.768459

[5 rows x 9 columns]

In [12]:
#confusion matrix
# Import necessary libraries
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Create Decision Tree classifier with entropy criterion
dtree_entropy = DecisionTreeClassifier(criterion='entropy')

# Fit the model on training data
dtree_entropy.fit(predictors_train, target_train)

# Make predictions on test data
prediction = dtree_entropy.predict(predictors_test)

# Calculate accuracy
accuracy = accuracy_score(target_test, prediction)
print(f"Accuracy: {accuracy:.4f}")


# Generate confusion matrix
cm = confusion_matrix(target_test, prediction)
print("\nConfusion Matrix:")
print(cm)
print(cm.shape)

# Optional: Display classification report for detailed metrics
print("\nClassification Report:")
print(classification_report(target_test, prediction))


Accuracy: 0.7407

Confusion Matrix:
[[6 0 0 0 0 0]
 [0 4 0 0 0 1]
 [0 0 2 0 0 0]
 [0 0 0 2 0 0]
 [0 1 0 1 4 0]
 [0 1 0 2 1 2]]
(6, 6)

Classification Report:
              precision    recall  f1-score   support

         adi       1.00      1.00      1.00         6
         car       0.67      0.80      0.73         5
         con       1.00      1.00      1.00         2
         fad       0.40      1.00      0.57         2
         gla       0.80      0.67      0.73         6
         mas       0.67      0.33      0.44         6

    accuracy                           0.74        27
   macro avg       0.76      0.80      0.75        27
weighted avg       0.78      0.74      0.73        27



In [21]:
#4
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
data =pd.read_csv('/content/btissue.csv')
X = data.iloc[:, :-1]
Y= data.iloc[:, -1]
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)
rf =RandomForestClassifier(random_state =123)
rf.fit(X_train, Y_train)
Y_pred =rf.predict(X_test)
print(accuracy_score(Y_test,Y_pred))



0.7727272727272727


In [26]:
#5
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
data =pd.read_csv('auto_mpg.csv')
data
data =data.dropna(axis=0,how='any')
data
X = data.iloc[:,1:8]
Y= data.iloc[:,0]
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)
model =LinearRegression()
model.fit(X_train,Y_train)
Y_pred =model.predict(X_test)
mse =mean_squared_error(Y_test,Y_pred)
r2 =r2_score(Y_test,Y_pred)
print(mse)
print(r2)

10.170693695667032
0.8363664681024057
